# backend/app/models/message.py
from sqlalchemy import Column, String, ForeignKey, Text, Integer, Float
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID
from app.db.base import Base, TimestampMixin, UUIDMixin


class Message(Base, UUIDMixin, TimestampMixin):
    """
    Every chat message — both from user and from the bot.
    session_id groups messages into one conversation.
    """
    __tablename__ = "messages"

    # "user" = typed by the human, "assistant" = generated by AI
    role       = Column(String(20), nullable=False)
    content    = Column(Text, nullable=False)

    # Groups messages into one conversation session
    session_id = Column(String(100), nullable=False, index=True)

    # How many tokens this response used — for billing/metering
    tokens_used = Column(Integer, default=0)

    # Feedback from user (thumbs up/down)
    feedback    = Column(String(10), nullable=True)  # "positive" | "negative"

    # Foreign keys
    chatbot_id = Column(UUID(as_uuid=True), ForeignKey("chatbots.id", ondelete="CASCADE"), nullable=False)
    tenant_id  = Column(UUID(as_uuid=True), ForeignKey("tenants.id",  ondelete="CASCADE"), nullable=False, index=True)

    # Relationships
    chatbot = relationship("Chatbot", back_populates="messages")
    tenant  = relationship("Tenant")

    def __repr__(self):
        return f"<Message {self.role}: {self.content[:50]}>"